routes/user.php
<?php

Route::get('/dashboard', 'User\UserController@showDashboard')->name('dashboard');
Route::get('/account', 'User\UserController@showAccount')->name('account');
Route::get('/bookings', 'User\UserController@showBookings')->name('bookings');
Route::get('/account/edit', 'User\UserController@edit')->name('account.edit');
Route::post('/account/update', 'User\UserController@update')->name('account.update');
Route::post('/account/update/password', 'User\UserController@changePassword')->name('password.change');
Route::post('/account/update/email', 'User\UserController@changeEmail')->name('email.change');

//cancel booking
Route::get('/my/bookings/delete/{id}', 'User\UserController@cancelBooking')
    ->name('userCancelBooking');
Route::get('/my/bookings/pay/{id}', 'Glamping\BookController@confirm')
    ->name('userPayBooking');
Route::get('/my/bookings/delete/{id}/confirm', 'User\UserController@confirmCancelBooking')
    ->name('userConfirmCancelBooking');

//comments
Route::resource('comments', 'CommentController', ['only' => ['store']]);

routes/web.php
<?php

use App\Http\Controllers\Manager;
use App\Http\Controllers\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//homepage
Route::get('/', 'GlampingListController@index')->name('homepage');
//filter
Route::get('/filter', 'GlampingListController@showFilterPage')->name('filterPage');
Route::post('/filter', 'GlampingListController@showFilteredGlampings');
Route::any('/autocomplete', 'Glamping\GlampingController@getAutocompleteData');
Route::any('/autocomplete/impression', 'Glamping\ImpressionController@getAutocompleteData');

//feedback messages
Route::get('/feedback', 'MessageController@showFeedbackForm')->name('feedbackForm');
Route::post('/feedback/message', 'MessageController@setMessage')->name('setFeedbackMessage');

//social block
Route::get('/login/social/{provider}', 'Auth\SocialAccountController@login')->name('socialLogin');
Route::get('/login/social/callback/{provider}', 'Auth\SocialAccountController@callback');

//glamping page
Route::get('/glamping/{id}', 'User\UserController@showBookGlampingView')
    ->name('viewGlamping');
Route::post('/glamping/{id}', 'Glamping\BookController@createBook')
    ->name('createBook');
Route::post('/booking/new/info', 'Glamping\BookController@showAdditionalInfoForm')
    ->name('bookAdditionalInfo');
Route::post('booking/new', 'Glamping\BookController@createBookingFromUserForm')
    ->name('createBookingFromUserForm');
Route::post('/glamping/{id}/ajax', 'Glamping\GlampingController@getSimpleFilterResult');
Route::get('/glamping/get_prices/{glamping_id}/{from_date}/{to_date}', 'Glamping\BookController@getBuildingsPrices')
    ->name('newBookDatePrices');

Route::resource('page', 'PageController');

Route::group(['prefix' => 'user', 'namespace' => 'User\Auth'], function () {

    Route::get('/login', 'LoginController@showLoginForm')->name('user_login_page');
    Route::post('/login', 'LoginController@login')->name('user_login');

    Route::get('/register', 'RegisterController@showRegistrationForm')->name('user_register_page');
    Route::post('/register', 'RegisterController@register')->name('user_register');

    Route::get('/verifyemail/{token}', 'RegisterController@verify');

    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'ResetPasswordController@reset');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'manager', 'namespace' => 'Manager\Auth'], function () {

    Route::get('/login', 'LoginController@showLoginForm')->name('manager_login_page');
    Route::post('/login', 'LoginController@login')->name('manager_login');

    Route::get('/register', 'RegisterController@showRegistrationForm')->name('manager_register_page');
    Route::post('/register', 'RegisterController@register')->name('manager_register');

    Route::get('/verifyemail/{token}', 'RegisterController@verify');

    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'ResetPasswordController@reset');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm');
});

Route::post('/logout', function () {
    if (Auth::guard('manager')->check()) {
        $controller = new Manager\Auth\LoginController();
        return $controller->logout(request());
    }
    if (Auth::guard('user')->check()) {
        $controller = new User\Auth\LoginController();
        return $controller->logout(request());
    }
    return App::make('GlampingListController')->index();
})->name('logout');

Route::get('/get_captcha/{config?}', function (\Mews\Captcha\Captcha $captcha, $config = 'default') {
    return $captcha->src($config);
});

//delete comment
Route::resource('comments', 'CommentController', ['only' => ['destroy']]);

Route::get('/booking', function(){
    return view('booking');
});

app/Http/Controllers/Manager/AdminController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Traits\ProfileEditor;
use App\Http\Controllers\Controller;
use App\Http\Requests\Manager\AnswerRequest;
use App\Models\Communication\Message;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class AdminController extends Controller
{
    use ProfileEditor;
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showDashboard()
    {
        return view('manager.admin.dashboard');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit()
    {
        return view('manager.admin.edit_account_form');
    }

    /**
     * @param Request $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function update(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'patronomic' => 'nullable|string|max:255'
        ]);

        $this->saveChanges($request, 'Admin');

        return redirect()->back();
    }

    /**
     * @param Request $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function changeEmail(Request $request)
    {
        $this->saveEmail($request, 'manager');

        return redirect()->back();
    }

    /**
     * @return $this
     */
    public function showFeedbackMessages()
    {
        return view('manager.message.index',[
            'gridData' => Message::all(),
            'breadCrumbsActive' => 'feedbackMessages',
            'active' => 'Feedback',
            'pageName' => trans('messages.feedbackMessagesGrid')
        ]);
    }


    /**
     * Show message
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showMessage($id)
    {
        $message = Message::find($id);

        if(!$message->viewed){

            $message->update([
                'viewed' => 1
            ]);
        }
        return view('manager.message.show', [
            'breadCrumbsActive' => 'feedbackMessages',
            'active' => 'Feedback',
            'pageName' => $message->name,
            'message' => $message
        ]);
    }

    /**
     * Toggle viewed option
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function toggleViewed(Request $request)
    {
        $message = Message::find($request->mes_id);
        $message->update([
            'viewed' => $request->val
        ]);

        return response()->json(['status' => true]);
    }

    /**
     * Sending answer on user question
     *
     * @param AnswerRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function answerMessage(AnswerRequest $request)
    {

        $mess = Message::find($request->message);

        Mail::send('manager.emails.answer', ['ask' => $mess->message, 'answer' => $request->answer], function ($message)  use ($mess){

            $message->to($mess->email)->subject('Answer ur question!');
        });

        return redirect()->route('manager.feedbackMessages');
    }
}

app/Http/Controllers/Manager/ApplicationController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Jobs\SendRegistrationEmail;
use App\Models\Auth\Manager;
use App\Models\Communication\ApplicationType;
use App\Models\Glamping\Glamping;
use App\Models\Communication\Application;
use App\Models\Communication\ApplicationStatus;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Helpers\ResourceControllerHelper as ResourceHelper;
use Illuminate\Support\Facades\Validator;

class ApplicationController extends Controller
{
    /**
     * @return ApplicationController
     */
    public function index()
    {
        $columns = ['type', 'description', 'date-application', 'action-view'];

        return $this->renderGrid($columns);
    }

    /**
     * @return ApplicationController
     */
    public function archive()
    {
        $columns = ['type', 'description', 'date-application', 'date-review',
            'status', 'action-view'];

        return $this->renderGrid($columns, true);
    }

    /**
     * @param $columns
     * @param bool $archive
     * @return $this
     */
    private function renderGrid($columns, $archive = false) {
        if ($archive) {
            $active = 'ApplicationArchive'; $crumbs = 'archive';
        } else {
            $active = 'Application'; $crumbs = 'new';
        }

        return view('manager.abstract_model.grid')->with([
            'pageName' => trans('applications.gridName'),
            'columns' => ResourceHelper::getColumnGridData($columns),
            'active' => $active,
            'breadCrumbsActive' => $crumbs,
            'gridData' => $this->getApplicationGridData($archive),
            'arrayGridData' => true,
            'viewRoute' => 'manager.applications.show',
            'menuItem' => 'applications'
        ]);
    }

    /**
     * @param $glampingId
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function send($glampingId)
    {
        $glamping = Glamping::find($glampingId);

        if (is_null($glamping))
            return redirect()->back()->withErrors(trans('messages.notExistGlampingError'));

        if (Auth::guest() || !Auth::user()->glampings->contains($glamping->id))
            return redirect()->back()->withErrors(trans('messages.noRightsToThisGlamping'));

        if ($glamping->accepted) {
            $app = new Application;
            $app->forceFill(['type' => ApplicationType::CHANGE]);
            $result = $glamping->applications()->save($app);
        }else {
            $app = new Application;
            $app->forceFill(['type' => ApplicationType::CREATE]);
            $result = $glamping->applications()->save($app);
        }

        if (!$result)
            redirect()->back()->withErrors(trans('messages.dangerMessage'));

        return redirect()->back();
    }

    /**
     * @param bool $archive
     * @return array|null
     */
    private function getApplicationGridData($archive = false)
    {
        $gridData = null;
        $applications = Application::where('is_viewed', $archive)->get();

        foreach ($applications as $app) {
            $gridData[] = [
                'type' => $app->getType(),
                'description' => $app->getDescription(),
                'date-application' => date_create($app->created_at)->format('d.m.Y H:i'),
                'date-review' => date_create($app->updated_at)->format('d.m.Y H:i'),
                'id' => $app->id,
                'status' => $app->getStatus(),
                'reviewer' => $app->reviewer,
                'viewRoute' => 'manager.applications.show',
            ];
        }

        return $gridData;
    }

    /**
     * @param Request $request
     */
    private function validateApplicationData(Request $request)
    {
        Validator::make($request->all(), ['answer' => 'nullable|string|min:3|max:500'])
            ->after(function ($validator) use ($request) {
            if (isset($request->reject) && is_null($request->answer))
                $validator->errors()->add('', trans('messages.emptyDenyMessage'));

            if (!isset($request->reject) && !isset($request->approve))
                $validator->errors()->add('', trans('messages.unknownApplicationStatus'));
        })->validate();
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $this->validateApplicationData($request);
        $app = Application::find($id);

        if (is_null($app))
            redirect()->back()->withErrors(trans('messages.notExistApplicationError',
                ['id' => htmlspecialchars($id)]));

        $status = ApplicationStatus::REJECTED;
        $message = trans('messages.rejectApplicationMessage');

        if (isset($request->approve)) {
            $message = trans('messages.approveApplicationMessage');
            $status = ApplicationStatus::ACCEPTED;

            if ($app->applicationable_type === 'glamping')
                $this->acceptGlamping($app->applicationable);
            else
                $this->acceptAndNotifyOwner($app->applicationable, $app->type);
        }

        $result = $app->forceFill([ 'status' => $status, 'answer' =>$request->answer,
            'manager_id' => Auth::user()->id, 'is_viewed' => true])->update();

        if ($app->type === ApplicationType::REGISTER)
            dispatch(new SendRegistrationEmail($app->applicationable, ApplicationStatus::REJECTED));

        if (!$result)
            flash(trans('messages.dangerMessage'), 'danger');

        flash($message, 'success');

        return redirect()->back();
    }

    /**
     * @param $owner
     * @param $appType
     * @return $this
     */
    private function acceptAndNotifyOwner($owner, $appType)
    {
        $result = $owner->forceFill(['accepted' => true])->update();
        if (!$result)
            return redirect()->back()->withErrors(trans('messages.dangerMessage'));

        if ($appType === ApplicationType::REGISTER)
            dispatch(new SendRegistrationEmail($owner, ApplicationStatus::ACCEPTED));
    }

    /**
     * @param $glamping
     * @return $this
     */
    private function acceptGlamping($glamping)
    {
        if ($glamping->changedGlamping) {
            $result = $glamping->forceFill(['active' => false, 'accepted' => false])->update();

            if (!$result)
                return redirect()->back()->withErrors(trans('messages.dangerMessage'));

            $result = $glamping->changedGlamping->forceFill([
                'active' => true, 'accepted' => true])->update();

            if (!$result)
                return redirect()->back()->withErrors(trans('messages.dangerMessage'));

            foreach ($glamping->buildings as $building) {
                $this->saveApplicationableBuilding($building,
                    $glamping->changedGlamping->id);
            }
        } else {
            $result = $glamping->forceFill([
                'active' => true, 'accepted' => true])->update();

            if (!$result)
                return redirect()->back()->withErrors(trans('messages.dangerMessage'));

            foreach ($glamping->buildings as $building) {
                $this->saveApplicationableBuilding($building, $glamping->id);
            }
        }
    }

    /**
     * @param $building
     * @param $applicationableId
     * @return $this
     */
    private function saveApplicationableBuilding($building, $applicationableId)
    {
        if ($building->changedBuilding) {
            $result = $building->changedBuilding->forceFill([
                'active' => true,
                'accepted' => true,
                'glamping_id' => $applicationableId])->update();

            if (!$result)
                return redirect()->back()->withErrors(trans('messages.dangerMessage'));

            $result = $building->forceFill([
                'active' => false,
                'accepted' => false
            ])->update();

            if (!$result)
                return redirect()->back()->withErrors(trans('messages.dangerMessage'));
        } else {
            $result = $building->forceFill([
                'active' => true,
                'accepted' => true,
                'glamping_id' => $applicationableId])->update();

            if (!$result)
                return redirect()->back()->withErrors(trans('messages.dangerMessage'));
        }
    }

    /**
     * @param $id
     * @return $this
     */
    public function show($id)
    {
        $app = Application::find($id);

        if (is_null($app))
            return redirect()->back()->withErrors(trans('messages.notExistApplicationError',
                ['id' => htmlspecialchars($id)]));

        return view('manager.admin.application')->with([
            'app' => $app,
            'reviewer' => Manager::find($app->manager_id)
        ]);
    }
}

resources/views/manager/page/index.blade.php
@extends('layouts.admin_dashboard')

@section('additional_styles')
    <!-- JQuery DataTable Css -->
    <link href="{{ asset('theme/assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endsection

@section('pages_status')active @endsection

@section('page_name'){{ trans('common_elements.' . $breadCrumbsActive) }}@endsection

@section('bread_crumbs')
    <li><a href="{{ route('manager.admin_dashboard') }}">{{ trans('common_elements.home') }}</a></li>
    <li class="active">{{ trans('common_elements.' . $breadCrumbsActive) }}</li>
@endsection


@section('content_name')
    <div class="header">
        <h2>{{ $pageName or NULL }}</h2>
    </div>
@endsection

@section('content')

    <table class="table table-bordered table-striped table-hover js-basic-example">
        <thead>
        <tr>
            <th class="text-center sorting">#</th>
            <th class="text-center sorting">Name</th>
            <th class="text-center sortable-false">Description</th>
            <th class="text-center sortable-false" >Action</th>
        </tr>
        </thead>
        <tbody>
        @forelse($pages as $page)
            <tr>
                <td>{{$page->id}}</td>
                <td>{{$page->name}}</td>
                <td>{!! str_limit($page->description, 70, "...") !!}</td>
                <td class="text-center">
                    <a href="{{route('manager.page', ['id' => $page->id])}}">
                        <i class="material-icons text-info">edit</i>
                    </a>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="4" class="text-center">Нет страниц</td>
            </tr>
        @endforelse
        </tbody>
    </table>
@endsection

@section('additional_scripts')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="{{ asset('theme/assets/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="{{ mix('js/confirm_alert.js') }}"></script>

@endsection

resources/views/manager/page/show.blade.php
@extends('layouts.admin_dashboard')

@section('additional_styles')
    <!-- JQuery DataTable Css -->
    <link href="{{ asset('theme/assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endsection

@section('page_name'){{ trans('common_elements.' . $breadCrumbsActive) }}@endsection

@section('bread_crumbs')
    <li><a href="{{ route('manager.admin_dashboard') }}">{{ trans('common_elements.home') }}</a></li>
    <li>
        <a href="{{route('manager.pages')}}">
            {{ trans('common_elements.' . $breadCrumbsActive) }}
        </a>
    </li>
    <li class="active">{{$pageName}}</li>
@endsection


@section('content_name')
    <div class="header">
        <h2>{{ $pageName or NULL }}</h2>
    </div>
@endsection

@section('content')
        <div class="wrapper-show-page">
            <form action="{{route('manager.page.update',['id' => $page->id])}}" method="post">
                {{csrf_field()}}
                {{method_field('PUT')}}
                <ul class="nav nav-tabs tab-nav-right" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#rus" data-toggle="tab" aria-expanded="true">Rus</a>
                    </li>
                    <li role="presentation" class="">
                        <a href="#eng" data-toggle="tab" aria-expanded="false">Eng</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane fade active in" id="rus">
                        <div class="row">
                            <div class="col-sm-4 col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line focused">
                                        <input type="text" class="form-control" name="name:ru" value="{{$page->translate('ru')->name}}">
                                        <label class="form-label">{{trans('common_elements.pageName')}}</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4 col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line focused">
                                        <input type="text" class="form-control" name="title:ru" value="{{$page->translate('ru')->title}}">
                                        <label class="form-label">{{trans('common_elements.pageTitle')}}</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4 col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line focused">
                                        <input type="text" class="form-control" name="keywords:ru" value="{{$page->translate('ru')->keywords}}">
                                        <label class="form-label">{{trans('common_elements.pageKeywords')}}</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-xs-12">
                                <div class="form-group form-float">
                                    <label class="form-label">{{trans('common_elements.pageDescription')}}</label>
                                    <textarea name="description:ru" id="desc_ru" required>{!!$page->translate('ru')->description !!}</textarea>
                                </div>
                            </div>
                            <div class="col-sm-6 col-xs-12">
                                <div class="form-group form-float">
                                    <label class="form-label">{{trans('common_elements.pageSeoDescription')}}</label>
                                        <textarea id="seo_desc_ru" name="seo_description:ru" required>{!!  $page->translate('ru')->seo_description!!}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="eng">
                        <div class="row">
                            <div class="col-sm-4 col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line focused">
                                        <input type="text" class="form-control" name="name:en" value="{{$page->translate('en')->name}}" required>
                                        <label class="form-label">{{trans('common_elements.pageName')}}</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4 col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line focused">
                                        <input type="text" class="form-control" name="title:en" value="{{$page->translate('en')->title}}" required>
                                        <label class="form-label">{{trans('common_elements.pageTitle')}}</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4 col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line focused">
                                        <input type="text" class="form-control" name="keywords:en" value="{{$page->translate('en')->keywords}}">
                                        <label class="form-label">{{trans('common_elements.pageKeywords')}}</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-xs-12">
                                <div class="form-group form-float">
                                    <label class="form-label">{{trans('common_elements.pageDescription')}}</label>
                                    <textarea id="desc_en" name="description:en">{{$page->translate('en')->description}}</textarea>
                                </div>
                            </div>
                            <div class="col-sm-6 col-xs-12">
                                <div class="form-group form-float">
                                    <label class="form-label">{{trans('common_elements.pageSeoDescription')}}</label>
                                    <textarea id="seo_desc_en" name="seo_description:en">{{$page->translate('en')->seo_description}}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <button class="btn btn-raised waves-effect bg-indigo" type="submit">
                        Обновить
                    </button>
                </div>
            </form>
        </div>
@endsection

@section('additional_scripts')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('theme/assets/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="{{ asset('theme/assets/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="{{ asset('js/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ mix('js/confirm_alert.js') }}"></script>
    <script src="{{ asset('js/page/show.js') }}"></script>
@endsection